# Generated by Django 4.2.28 on 2026-02-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente'), ('overdue', 'Vencido')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted', 'active'], name='clients_cli_is_dele_027dab_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['payment_status', 'next_payment_date'], name='clients_cli_payment_bdafd0_idx'),
        ),
    ]
