# Generated by Django 4.2.28 on 2026-02-12 02:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Especialización')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de contratación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Capacidad máxima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('opening_time', models.TimeField(default='06:00', verbose_name='Hora apertura')),
                ('closing_time', models.TimeField(default='22:00', verbose_name='Hora cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JumpingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la clase')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('capacity', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad máxima')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Participantes actuales')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('all', 'Todos los niveles')], default='all', max_length=20, verbose_name='Dificultad')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('full', 'Completa')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Precio')),
                ('requires_equipment', models.BooleanField(default=True, verbose_name='Requiere equipo')),
                ('equipment_available', models.PositiveIntegerField(default=15, verbose_name='Equipos disponibles')),
                ('recurring', models.BooleanField(default=False, verbose_name='Clase recurrente')),
                ('recurring_days', models.JSONField(blank=True, default=list, verbose_name='Días de repetición')),
                ('recurring_until', models.DateField(blank=True, null=True, verbose_name='Repetir hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='jumping.instructor', verbose_name='Instructor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='jumping.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Clase de Jumping',
                'verbose_name_plural': 'Clases de Jumping',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('jumping', 'Cama elástica'), ('mat', 'Colchoneta'), ('weight', 'Pesa'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('available_quantity', models.PositiveIntegerField(default=1, verbose_name='Disponibles')),
                ('condition', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Bueno'), ('fair', 'Regular'), ('poor', 'Malo'), ('damaged', 'Dañado')], default='good', max_length=20, verbose_name='Condición')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='jumping.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha reserva')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('attended', 'Asistió'), ('no_show', 'No asistió')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Pagado')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto pagado')),
                ('attended', models.BooleanField(default=False, verbose_name='Asistió')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de llegada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jumping_bookings', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('jumping_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='jumping.jumpingclass', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.AddIndex(
            model_name='jumpingclass',
            index=models.Index(fields=['date', 'status'], name='jumping_jum_date_6f81ef_idx'),
        ),
        migrations.AddIndex(
            model_name='jumpingclass',
            index=models.Index(fields=['location', 'date'], name='jumping_jum_locatio_5a0efa_idx'),
        ),
        migrations.AddIndex(
            model_name='jumpingclass',
            index=models.Index(fields=['instructor', 'date'], name='jumping_jum_instruc_1862d0_idx'),
        ),
        migrations.AddIndex(
            model_name='classbooking',
            index=models.Index(fields=['status', 'payment_status'], name='jumping_cla_status_bf4785_idx'),
        ),
        migrations.AddIndex(
            model_name='classbooking',
            index=models.Index(fields=['jumping_class', 'status'], name='jumping_cla_jumping_4e8aff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classbooking',
            unique_together={('client', 'jumping_class')},
        ),
    ]
