# Generated by Django 6.0.2 on 2026-02-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsnotification',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='smsnotification',
            name='sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smsnotification',
            name='status',
            field=models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('failed', 'Fallido'), ('undelivered', 'No entregado')], max_length=20),
        ),
    ]
