# Generated by Django 4.2.28 on 2026-02-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_sent_at_smsnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
